### ISSUE TITLE
WalkableArea visibility inconsistencies

### ISSUE THREAD

**Issue by drbbgh** [carenalgas/popochiu#325] opened 2024-10-30 15:53 UTC
### Bug description

Despite having the 'Always Show Walkable Areas' option on in the Editor Settings, walkable areas lose visibility under certain conditions. 

###  Steps to reproduce

Case 1:
1. Open a room scene
2. Click on a walkable area node in the 2D view
3. Click outside the walkable area
4. The walkable area disappears

Case 2:
1. Open a room scene
2. Double click on any node in the 2D view
3. Close the node editing window or simply go back to the room scene
4. The walkable area has disappeared and its visibility state is inconsistent (enable on/off to reset)

### Expected vs observed behavior

Walkable areas should always be visible in the room scene if 'Always Show Walkable Areas' option is on.
At the moment walkable areas do not behave accordingly.

### Environment information (please complete):

 - **OS type and version**: `Linux Acer 6.11.2-4-MANJARO #1 SMP PREEMPT_DYNAMIC Tue Oct  8 11:52:01 UTC 2024 x86_64 GNU/Linux`
 - **Godot version**: 4.3
 - **Plugin version or branch**: 2.0 develop

### Additional context

https://github.com/user-attachments/assets/2aade25b-923a-405d-a11c-2c70fd61b2f9

**Comment by stickgrinder** [comment] 2024-11-01 20:52
Case 1 is solved.
Case 2 is confirmed but yet to be solved. Working on it.

**Comment by stickgrinder** [comment] 2024-11-01 21:34
Can't track the root cause of Case 2. It's pretty annoying.

Tried to queue a redraw of the polygon when the node is made visible, but it doesn't work.

Adding that ANY change in the inspector, even at other nodes in the same scene, will redraw the WA polygon.

**Comment by stickgrinder** [comment] 2024-11-02 15:42
I can't track the problem and I actually think it's a problem with Godot, not the plugin.
To support this:

- the problem is not that the walkable area polygon is invisibile/hidden, but that Godot does not paint the inside polygon
- if you click the button to edit the polygon, the outline is shown, but the internal polygon overlay is not (again)
- baking the polygon while editing works and the polygon is shown
- not baking the polygon leaves things as they are (no visible polygon)
- touching ANYTHING in the inspector, even on other nodes, make the polygon suddenly visible
- making the WA invisible and than visible again shows the polygon
- closing and opening the scene shows the polygon

I chased many different options but got nowhere: it seems that from the script I can't solve this.

Since Case 1 has been addressed and since the next issue in line is a custom gizmo for polygon editing, I'll skip this fix for now.

**Closed** 2024-11-02 15:43 UTC
Labels: bug
